      <hr id="fadeIn2">

      <footer id="fadeIn3">
        <p>
	        <span class="propos">
	        	<a href="http://www.facebook.com/pages/Grumpyer-Community/391000940984709?ref=hl" target="_blank">
	        		A propos
	        	</a>
	        </span>
	        <span class="mail">
	        	 <a href="mailto:contact@grumpyer.com">
	        	 	Contact
	        	 </a>
	        </span>
	        <span class="twitter-footer">
	        	<a href="http://www.twitter.com/GrumpyerApp" target="_blank">
	        		Twitter
	        	</a>
	        </span>
	        <span class="facebook-footer">
	        	<a href="http://www.facebook.com/appcenter/grumpyer" target="_blank">
	        		Facebook
	        	</a>
	        </span>
	        <span class="conditions">
	        	<a href="http://www.facebook.com/legal/terms" target="_blank">
	        		Conditions
	        	</a>
	        </span>
	        <span class="confidentiality">
	        	<a href="http://www.facebook.com/about/privacy" target="_blank">
	        		Confidentialité
	        	</a>
	        </span>
        	<span class="copyright">Grumpyer &copy; 2013</span>
        </p>
      </footer>
  </body>
</html>