<?php session_start() ?>
<?php require 'library/facebook/params_facebook.php'; ?>
<!DOCTYPE html>
<html lang="fr">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# grumpyer: http://ogp.me/ns/fb/grumpyer#">
    <meta charset="utf-8">
    <title>Grumpyer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Meta Facebook -->
  <meta property="fb:app_id" content="127244637430412" /> 
  <meta property="og:type"   content="grumpyer:brand" /> 
  <meta property="og:url"    content="http://grumpyer.com" />
  <meta property="og:title"  content="Grumpyer" /> 
  <meta property="og:image"  content="http://grumpyer.com/public/img/app-logo.png" />
  
    <!-- Le styles -->
    <link href="public/css/bootstrap.css" rel="stylesheet">
    <link href="public/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="public/css/style.css" rel="stylesheet">
    <link href="public/css/jquery.autocomplete.css" rel="stylesheet">
    
    <!-- JQuery -->
    <script type="text/javascript" src="public/js/jquery.js"></script>
    
    <!-- JS Bootstrap-->
    <script type="text/javascript" src="public/js/bootstrap.js"></script>
    <script type="text/javascript" src="public/js/bootstrap.min.js"></script>
    
    <!-- JS Fadein FadeOut -->
    <script type="text/javascript" src="public/js/fadein.js"></script>
    <script type="text/javascript" src="public/js/fadeout.js"></script>
    
    <!-- JS JQuery Autocomplete -->
    <script type="text/javascript" src="public/js/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="public/js/autocomplete.js"></script>
    
    <!-- JS Scroll -->
    <?php if ($_SERVER['PHP_SELF'] == '/brands.php') : ?>
    <script type="text/javascript" src="public/js/scroll.js"></script>
    <?php elseif ($_SERVER['PHP_SELF'] == '/profile.php') : ?>
    <script type="text/javascript" src="public/js/scrollProfile.js"></script>
    <?php else : ?>
    <?php endif; ?>
    
    <!-- JS Delete -->
    <script type="text/javascript" src="public/js/delete.js"></script>
    
    <!-- JS Add -->
    <script type="text/javascript" src="public/js/add.js"></script>
    
    <!-- JS Ancres -->
    <?php if (isset($_POST['grumper'])) { ?>
    <script type="text/javascript" src="public/js/ancre-add.js"></script>
	<?php } ?>
	
	<?php if (isset($_POST['propose-btn'])) { ?>
    <script type="text/javascript" src="public/js/ancre-propose.js"></script>
	<?php } ?>
	
	<!-- JS Caroussel -->
	<script src="public/js/caroussel.js" type="text/javascript"></script>
	
	<!-- JS Analytics -->
	<script type="text/javascript" src="public/js/analytics.js"></script>
    
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="public/img/favicon.ico">
  </head>
  <body>
  <?php include 'loader.php'; ?>
  
  <div id="fb-root"></div>
  
  <!-- Facebook Invite Friends -->
  <script src="http://connect.facebook.net/fr_FR/all.js" type="text/javascript"></script>
  <script type="text/javascript" src="public/js/fb-invite-friends.js"></script>