    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        <?php if ($user) { ?>
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
          </a>
        <?php } ?>
          <a class="brand" href="index.php"><img src="public/img/logo.png" /></a>
          <div class="nav-collapse collapse">
          <?php if ($user) { ?>
          <ul class="nav">
          <?php if ($_SERVER['PHP_SELF'] == '/index.php') { ?>
            <li class="active">
          		<a href="index.php">
          			<i class="icon-home icon-white"></i> 
          			<b>Accueil</b>
          		</a>
          	</li>
          <?php } else { ?>
            <li>
          		<a href="index.php">
          			<i class="icon-home icon-white"></i> 
          			<b>Accueil</b>
          		</a>
          	</li>          
          <?php } ?>
          <?php if ($_SERVER['PHP_SELF'] == '/search.php') { ?>
            <li class="active">
          		<a href="brands.php">
          			<i class="icon-globe icon-white"></i> 
          			<b>Marques</b>
          		</a>
          	</li>
          	<?php } else { ?>
            <li>
          		<a href="brands.php">
          			<i class="icon-globe icon-white"></i> 
          			<b>Marques</b>
          		</a>
          	</li>
          	<?php } ?>
          	<?php if ($_SERVER['PHP_SELF'] == '/profile.php') { ?>
          	<li class="active">
          		<a href="profile.php">
          			<i class="icon-user icon-white"></i> 
          			<b>Mon profil</b>
          		</a>
          	</li>
          	<?php } else { ?>
          	<li>
          		<a href="profile.php">
          			<i class="icon-user icon-white"></i> 
          			<b>Mon profil</b>
          		</a>
          	</li>
          	<?php } ?>
          	<?php if ($_SERVER['PHP_SELF'] == '/administration.php' 
          			  && $user_profile['id'] == '100004333361936') : ?>
          	<li class="active">
          		<a href="administration.php">
          			<i class="icon-briefcase icon-white"></i> 
          			<b>Administration</b>
          		</a>
          	</li>          	
          	<?php elseif($user_profile['id'] == '100004333361936') : ?>
          	<li>
          		<a href="administration.php">
          			<i class="icon-briefcase icon-white"></i> 
          			<b>Administration</b>
          		</a>
          	</li>          	
          	<?php else : endif;?>
		  </ul>
		  <?php } ?>
		  </div>
        </div>
      </div>
    </div>  